

-- This file was automatically generated by natural4.
-- Do not edit by hand.
-- Instead, revise the toolchain starting at smucclaw/dsl/lib/haskell/natural4/app/Main.hs

module RuleLib.PDPADBNO where

import Prelude
import Data.Either
import Data.Maybe
import Data.Tuple
import Data.Map as Map

import AnyAll.Types

schedule1_part1 :: Item String
schedule1_part1 =

   All
    ( Pre "all of:" )
    [ Leaf "Are you a public agency?"
    , Leaf "Does the data breach occur on or after the date of commencement of PDP(A)A_2020_§13?"
    ]



schedule1_part1_nl :: NLDict
schedule1_part1_nl =
  Map.fromFoldable
    [ ]
    

toplevelDecisions :: Map.Map (String) (Item String)
toplevelDecisions = Map.fromFoldable [ Tuple "Assess"
    ( All
        ( Pre "all of:" )
        [ Leaf "Organisation is not a Public Agency"
        , Leaf "the data breach occurs on or after the date of commencement of PDP(A)A 2020 §13"
        ]
    )
]
toplevelDefaultMarking :: Marking
toplevelDefaultMarking = Marking $ Map.fromFoldable []