name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-gh-pages:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: npm run build
        env:
          VUE_APP_BROWSER_NAME: "CCLAW"
          VUE_APP_NAME: "PDPA DBNO PoC - Draft"
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
