name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test-purs:
    name: Test Purescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: npm run test:purs
  test-unit:
    name: test-frontend-unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: npm run test:unit
