name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test Purescript
        run: npm run test:purs
      - name: Test Components
        run: npm run test:unit
